{% set name = "pymodbus" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymodbus-{{ version }}.tar.gz
  sha256: 37c9b6f3e5c82f39ee42047ca48cbc9fd0c49a6731126789500191e9deea6cbc

build:
  number: 0
  noarch: python
  entry_points:
    - pymodbus.console=pymodbus.repl.client.main:main
    - pymodbus.server=pymodbus.repl.server.main:server
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - six
  run:
    - python >=3.6
    - aiohttp >=3.7.3
    - click >=7.0
    - prompt_toolkit >=3.0.8
    - pygments >=2.2.0
    - pyserial >=3.4
    - pyserial-asyncio >=0.5
    - six >=1.15.0

test:
  imports:
    - pymodbus
    - pymodbus.client
  requires:
    - pip
  commands:
    - pymodbus.console --help
    - pymodbus.server --help
    - pip check

about:
  home: https://github.com/riptideio/pymodbus/
  summary: A fully featured modbus protocol stack in python
  doc_url: https://pymodbus.readthedocs.io
  dev_url: https://github.com/riptideio/pymodbus
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saibhargav1508
    - beenje
